export default [
    {
        name:'Início',
        iconType:'Material',
        iconName:'home'
    },
    {
        name:'Usuário',
        iconType:'Material',
        iconName:'person'
    },
    {
        name:'Treino',
        iconType:'Material',
        iconName:'book'
    },
    {
        name:'Logout',
        iconType:'Material',
        iconName:'logout'
    }
 ]